"""
Site arayuzunun (buton, baslik, etiket metinleri) cok dilli metinleri.
Altyazi diliyle (translate.py) karistirilmasin - bu, sitenin kendi dilidir,
ziyaretcinin bulundugu ulkeye (IP) gore, bulunamazsa tarayici diline gore secilir.
"""

import json
import urllib.request
from typing import Optional

SUPPORTED_UI_LANGS = ["en", "es", "pt", "fr", "de", "it", "tr", "ar", "hi", "zh", "ja", "ko", "ru", "id"]
RTL_LANGS = {"ar"}

# ISO 3166-1 alpha-2 ulke kodu -> arayuz dili
COUNTRY_TO_LANG = {
    "US": "en", "GB": "en", "CA": "en", "AU": "en", "NZ": "en", "IE": "en", "ZA": "en",
    "ES": "es", "MX": "es", "AR": "es", "CO": "es", "CL": "es", "PE": "es", "VE": "es",
    "EC": "es", "GT": "es", "CU": "es", "BO": "es", "DO": "es", "HN": "es", "PY": "es",
    "SV": "es", "NI": "es", "CR": "es", "PA": "es", "UY": "es", "PR": "es",
    "PT": "pt", "BR": "pt",
    "FR": "fr", "BE": "fr", "LU": "fr", "MC": "fr",
    "DE": "de", "AT": "de", "CH": "de",
    "IT": "it", "SM": "it", "VA": "it",
    "TR": "tr",
    "SA": "ar", "AE": "ar", "EG": "ar", "IQ": "ar", "JO": "ar", "KW": "ar", "QA": "ar",
    "BH": "ar", "OM": "ar", "YE": "ar", "SY": "ar", "LB": "ar", "LY": "ar", "TN": "ar",
    "DZ": "ar", "MA": "ar", "SD": "ar",
    "IN": "hi",
    "CN": "zh", "HK": "zh", "TW": "zh", "MO": "zh",
    "JP": "ja",
    "KR": "ko", "KP": "ko",
    "RU": "ru", "BY": "ru", "KZ": "ru",
    "ID": "id",
}


def get_client_ip(request) -> str:
    forwarded = request.headers.get("CF-Connecting-IP") or request.headers.get("X-Forwarded-For")
    if forwarded:
        return forwarded.split(",")[0].strip()
    return request.remote_addr or ""


def get_country_lang(ip: str) -> Optional[str]:
    if not ip or ip.startswith(("127.", "10.", "192.168.", "::1")):
        return None
    try:
        url = f"http://ip-api.com/json/{ip}?fields=status,countryCode"
        with urllib.request.urlopen(url, timeout=1.5) as response:
            data = json.loads(response.read().decode("utf-8"))
        if data.get("status") == "success":
            return COUNTRY_TO_LANG.get(data.get("countryCode"))
    except Exception:
        return None
    return None

UI_STRINGS = {
    "en": {
        "eyebrow": "Made for solo creators &middot; Watermark-free &middot; Flat price",
        "headline": "Stylish captions for your video in <em>seconds</em> &mdash; no watermark, ever.",
        "lede": "Made for TikTok, Reels & Shorts creators. Upload your clip, pick a language, download instantly.",
        "cta_scroll": "Try it free ↓",
        "free_note": "Free plan: 3 videos a month, up to 90 seconds each &mdash; no watermark. Paid plans coming soon.",
        "demo_label": "Example caption style",
        "demo_caption": "This is how your captions look.",
        "how_it_works_title": "How it works",
        "step1_title": "Upload your clip",
        "step1_desc": "Any video file, straight from your phone or camera.",
        "step2_title": "Pick a language",
        "step2_desc": "Captions can be translated into 14 languages.",
        "step3_title": "Download, watermark-free",
        "step3_desc": "Most short clips are ready in under a minute.",
        "faq_title": "Frequently asked questions",
        "faq_q1": "Is it really free?",
        "faq_a1": "Yes. The free plan includes 3 videos a month, up to 90 seconds each, with zero watermark. Paid plans for more volume are coming soon.",
        "faq_q2": "What languages are supported?",
        "faq_a2": "Captions can be translated into 14 languages, and the site itself automatically shows in your language.",
        "faq_q3": "Will there be a watermark on my video?",
        "faq_a3": "Never &mdash; on the free plan or any future paid plan.",
        "faq_q4": "How long does it take?",
        "faq_a4": "Most short clips are ready in under a minute.",
        "label_video": "Video file",
        "label_language": "Caption language",
        "label_email": "Email address",
        "button_process": "Process &rarr;",
        "badge_ready": "&#10003; Ready",
        "result_headline": "Your video is <em>ready</em>.",
        "download": "Download &darr;",
        "back_link": "Process another video &rarr;",
        "error_limit_title": "You've used this month's free videos",
        "error_limit_body": "Free plan includes {limit} videos per month. Paid plans are coming soon — check back shortly!",
        "error_duration_title": "Video is too long",
        "error_duration_body": "Free plan supports videos up to {max_min} minutes. Try a shorter clip, or wait for paid plans.",
        "login_google": "Sign in with Google",
        "logout": "Log out",
        "login_prompt": "Sign in with Google to upload your video.",
        "pricing_title": "Pricing",
        "pricing_pro_desc": "20 videos a month, up to 5 minutes each — still no watermark.",
        "pricing_soon": "Coming soon",
        "per_month": "/mo",
        "processing_badge": "⏳ Processing",
        "processing_title": "Your video is being processed.",
        "processing_body": "This can take a few minutes for longer clips. This page refreshes automatically, or come back later — we'll email you when it's ready.",
        "processing_error_title": "Something went wrong",
        "processing_error_body": "We couldn't process your video due to an unexpected error. Please try again, or reach out if this keeps happening.",
        "pricing_premium_desc": "10 videos a month, up to 15 minutes each — still no watermark.",
        "trust_note": "🔒 HTTPS-encrypted connection. Google sign-in means we never see or store a password. Videos are deleted from our servers automatically after processing.",
        "cover_subs_label": "Video already has burned-in subtitles - cover them",
        "cover_subs_hint": "We won't erase the old subtitles - we place a clean bar over them before adding the new ones.",
        "cover_subs_before": "If not selected",
        "cover_subs_after": "If selected",
        "footer": "Subly is built by Nexi Digital.",
    },
    "es": {
        "eyebrow": "Hecho para creadores independientes &middot; Sin marca de agua &middot; Precio fijo",
        "headline": "Subtitulos con estilo en <em>segundos</em> &mdash; nunca con marca de agua.",
        "lede": "Hecho para creadores de TikTok, Reels y Shorts. Sube tu video, elige un idioma, descarga al instante.",
        "cta_scroll": "Pruébalo gratis ↓",
        "free_note": "Plan gratuito: 3 videos al mes, hasta 90 segundos cada uno &mdash; sin marca de agua. Los planes de pago llegan pronto.",
        "demo_label": "Ejemplo de estilo de subtitulo",
        "demo_caption": "Asi se veran tus subtitulos.",
        "how_it_works_title": "Como funciona",
        "step1_title": "Sube tu video",
        "step1_desc": "Cualquier archivo de video, directo desde tu telefono o camara.",
        "step2_title": "Elige un idioma",
        "step2_desc": "Los subtitulos se pueden traducir a 14 idiomas.",
        "step3_title": "Descarga sin marca de agua",
        "step3_desc": "La mayoria de los clips cortos estan listos en menos de un minuto.",
        "faq_title": "Preguntas frecuentes",
        "faq_q1": "¿Es realmente gratis?",
        "faq_a1": "Si. El plan gratuito incluye 3 videos al mes, hasta 90 segundos cada uno, sin marca de agua. Los planes de pago para mas volumen llegan pronto.",
        "faq_q2": "¿Que idiomas se admiten?",
        "faq_a2": "Los subtitulos se pueden traducir a 14 idiomas, y el sitio mismo se muestra automaticamente en tu idioma.",
        "faq_q3": "¿Mi video tendra marca de agua?",
        "faq_a3": "Nunca &mdash; ni en el plan gratuito ni en ningun plan de pago futuro.",
        "faq_q4": "¿Cuanto tiempo tarda?",
        "faq_a4": "La mayoria de los clips cortos estan listos en menos de un minuto.",
        "label_video": "Archivo de video",
        "label_language": "Idioma de subtitulos",
        "label_email": "Correo electronico",
        "button_process": "Procesar &rarr;",
        "badge_ready": "&#10003; Listo",
        "result_headline": "Tu video esta <em>listo</em>.",
        "download": "Descargar &darr;",
        "back_link": "Procesar otro video &rarr;",
        "error_limit_title": "Ya usaste tus videos gratis de este mes",
        "error_limit_body": "El plan gratuito incluye {limit} videos al mes. Los planes de pago llegan pronto.",
        "error_duration_title": "El video es demasiado largo",
        "error_duration_body": "El plan gratuito admite videos de hasta {max_min} minutos. Prueba un clip mas corto.",
        "login_google": "Iniciar sesión con Google",
        "logout": "Cerrar sesión",
        "login_prompt": "Inicia sesión con Google para subir tu video.",
        "pricing_title": "Precios",
        "pricing_pro_desc": "20 videos al mes, hasta 5 minutos cada uno — sigue sin marca de agua.",
        "pricing_soon": "Próximamente",
        "per_month": "/mes",
        "processing_badge": "⏳ Procesando",
        "processing_title": "Tu video se está procesando.",
        "processing_body": "Esto puede tardar unos minutos en clips más largos. Esta página se actualiza automáticamente, o vuelve más tarde — te avisaremos por email cuando esté listo.",
        "processing_error_title": "Algo salió mal",
        "processing_error_body": "No pudimos procesar tu video debido a un error inesperado. Intenta de nuevo, o contáctanos si esto persiste.",
        "pricing_premium_desc": "10 videos al mes, hasta 15 minutos cada uno — sigue sin marca de agua.",
        "trust_note": "🔒 Conexion cifrada (HTTPS). Con el inicio de sesion de Google nunca vemos ni guardamos una contrasena. Los videos se eliminan automaticamente de nuestros servidores tras el procesamiento.",
        "cover_subs_label": "El video ya tiene subtitulos incrustados - cubrirlos",
        "cover_subs_hint": "No borramos los subtitulos antiguos - colocamos una barra limpia encima antes de anadir los nuevos.",
        "cover_subs_before": "Si no se selecciona",
        "cover_subs_after": "Si se selecciona",
        "footer": "Subly esta construido por Nexi Digital.",
    },
    "pt": {
        "eyebrow": "Feito para criadores solo &middot; Sem marca d'agua &middot; Preco fixo",
        "headline": "Legendas estilosas em <em>segundos</em> &mdash; nunca com marca d'agua.",
        "lede": "Feito para criadores de TikTok, Reels e Shorts. Envie seu video, escolha um idioma, baixe na hora.",
        "cta_scroll": "Experimente grátis ↓",
        "free_note": "Plano gratuito: 3 videos por mes, ate 90 segundos cada &mdash; sem marca d'agua. Planos pagos em breve.",
        "demo_label": "Exemplo de estilo de legenda",
        "demo_caption": "Assim ficarao suas legendas.",
        "how_it_works_title": "Como funciona",
        "step1_title": "Envie seu video",
        "step1_desc": "Qualquer arquivo de video, direto do celular ou camera.",
        "step2_title": "Escolha um idioma",
        "step2_desc": "As legendas podem ser traduzidas para 14 idiomas.",
        "step3_title": "Baixe sem marca d'agua",
        "step3_desc": "A maioria dos clipes curtos fica pronta em menos de um minuto.",
        "faq_title": "Perguntas frequentes",
        "faq_q1": "E realmente gratis?",
        "faq_a1": "Sim. O plano gratuito inclui 3 videos por mes, ate 90 segundos cada, sem marca d'agua. Planos pagos para mais volume chegam em breve.",
        "faq_q2": "Quais idiomas sao suportados?",
        "faq_a2": "As legendas podem ser traduzidas para 14 idiomas, e o proprio site aparece automaticamente no seu idioma.",
        "faq_q3": "Meu video tera marca d'agua?",
        "faq_a3": "Nunca &mdash; nem no plano gratuito, nem em nenhum plano pago futuro.",
        "faq_q4": "Quanto tempo demora?",
        "faq_a4": "A maioria dos clipes curtos fica pronta em menos de um minuto.",
        "label_video": "Arquivo de video",
        "label_language": "Idioma da legenda",
        "label_email": "Endereco de email",
        "button_process": "Processar &rarr;",
        "badge_ready": "&#10003; Pronto",
        "result_headline": "Seu video esta <em>pronto</em>.",
        "download": "Baixar &darr;",
        "back_link": "Processar outro video &rarr;",
        "error_limit_title": "Voce ja usou seus videos gratis deste mes",
        "error_limit_body": "O plano gratuito inclui {limit} videos por mes. Os planos pagos chegam em breve.",
        "error_duration_title": "O video e muito longo",
        "error_duration_body": "O plano gratuito aceita videos de ate {max_min} minutos. Tente um video mais curto.",
        "login_google": "Entrar com o Google",
        "logout": "Sair",
        "login_prompt": "Entre com o Google para enviar seu vídeo.",
        "pricing_title": "Preços",
        "pricing_pro_desc": "20 vídeos por mês, até 5 minutos cada — ainda sem marca d'água.",
        "pricing_soon": "Em breve",
        "per_month": "/mês",
        "processing_badge": "⏳ Processando",
        "processing_title": "Seu vídeo está sendo processado.",
        "processing_body": "Isso pode levar alguns minutos em clipes mais longos. Esta página atualiza automaticamente, ou volte mais tarde — avisaremos por email quando estiver pronto.",
        "processing_error_title": "Algo deu errado",
        "processing_error_body": "Não conseguimos processar seu vídeo devido a um erro inesperado. Tente novamente, ou entre em contato se isso persistir.",
        "pricing_premium_desc": "10 vídeos por mês, até 15 minutos cada — ainda sem marca d'água.",
        "trust_note": "🔒 Conexao criptografada (HTTPS). Com o login do Google, nunca vemos nem guardamos uma senha. Os videos sao excluidos automaticamente dos nossos servidores apos o processamento.",
        "cover_subs_label": "O video ja tem legendas gravadas - cobri-las",
        "cover_subs_hint": "Nao apagamos as legendas antigas - colocamos uma barra limpa por cima antes de adicionar as novas.",
        "cover_subs_before": "Se nao selecionado",
        "cover_subs_after": "Se selecionado",
        "footer": "Subly e desenvolvido pela Nexi Digital.",
    },
    "fr": {
        "eyebrow": "Concu pour les createurs solo &middot; Sans filigrane &middot; Prix fixe",
        "headline": "Des sous-titres stylises en <em>secondes</em> &mdash; jamais de filigrane.",
        "lede": "Concu pour les createurs TikTok, Reels et Shorts. Importez votre clip, choisissez une langue, telechargez aussitot.",
        "cta_scroll": "Essayez gratuitement ↓",
        "free_note": "Plan gratuit : 3 videos par mois, jusqu'a 90 secondes chacune &mdash; sans filigrane. Plans payants bientot disponibles.",
        "demo_label": "Exemple de style de sous-titre",
        "demo_caption": "Voici a quoi ressembleront vos sous-titres.",
        "how_it_works_title": "Comment ca marche",
        "step1_title": "Importez votre clip",
        "step1_desc": "N'importe quel fichier video, direct depuis votre telephone ou camera.",
        "step2_title": "Choisissez une langue",
        "step2_desc": "Les sous-titres peuvent etre traduits en 14 langues.",
        "step3_title": "Telechargez sans filigrane",
        "step3_desc": "La plupart des courts clips sont prets en moins d'une minute.",
        "faq_title": "Questions frequentes",
        "faq_q1": "Est-ce vraiment gratuit ?",
        "faq_a1": "Oui. Le plan gratuit inclut 3 videos par mois, jusqu'a 90 secondes chacune, sans aucun filigrane. Des plans payants pour plus de volume arrivent bientot.",
        "faq_q2": "Quelles langues sont prises en charge ?",
        "faq_a2": "Les sous-titres peuvent etre traduits en 14 langues, et le site lui-meme s'affiche automatiquement dans votre langue.",
        "faq_q3": "Y aura-t-il un filigrane sur ma video ?",
        "faq_a3": "Jamais &mdash; ni sur le plan gratuit, ni sur un futur plan payant.",
        "faq_q4": "Combien de temps ca prend ?",
        "faq_a4": "La plupart des courts clips sont prets en moins d'une minute.",
        "label_video": "Fichier video",
        "label_language": "Langue des sous-titres",
        "label_email": "Adresse email",
        "button_process": "Traiter &rarr;",
        "badge_ready": "&#10003; Pret",
        "result_headline": "Votre video est <em>prete</em>.",
        "download": "Telecharger &darr;",
        "back_link": "Traiter une autre video &rarr;",
        "error_limit_title": "Vous avez utilise vos videos gratuites ce mois-ci",
        "error_limit_body": "Le plan gratuit inclut {limit} videos par mois. Les plans payants arrivent bientot.",
        "error_duration_title": "La video est trop longue",
        "error_duration_body": "Le plan gratuit accepte des videos jusqu'a {max_min} minutes. Essayez un clip plus court.",
        "login_google": "Se connecter avec Google",
        "logout": "Se déconnecter",
        "login_prompt": "Connectez-vous avec Google pour importer votre vidéo.",
        "pricing_title": "Tarifs",
        "pricing_pro_desc": "20 vidéos par mois, jusqu'à 5 minutes chacune — toujours sans filigrane.",
        "pricing_soon": "Bientôt disponible",
        "per_month": "/mois",
        "processing_badge": "⏳ Traitement en cours",
        "processing_title": "Votre vidéo est en cours de traitement.",
        "processing_body": "Cela peut prendre quelques minutes pour les clips plus longs. Cette page s'actualise automatiquement, ou revenez plus tard — nous vous enverrons un email dès que ce sera prêt.",
        "processing_error_title": "Un problème est survenu",
        "processing_error_body": "Nous n'avons pas pu traiter votre vidéo en raison d'une erreur inattendue. Veuillez réessayer, ou nous contacter si cela persiste.",
        "pricing_premium_desc": "10 vidéos par mois, jusqu'à 15 minutes chacune — toujours sans filigrane.",
        "trust_note": "🔒 Connexion chiffree (HTTPS). Avec la connexion Google, nous ne voyons ni ne stockons jamais de mot de passe. Les videos sont supprimees automatiquement de nos serveurs apres le traitement.",
        "cover_subs_label": "La video a deja des sous-titres incrustes - les recouvrir",
        "cover_subs_hint": "Nous n'effacons pas les anciens sous-titres - nous placons une barre propre par-dessus avant d'ajouter les nouveaux.",
        "cover_subs_before": "Si non coche",
        "cover_subs_after": "Si coche",
        "footer": "Subly est developpe par Nexi Digital.",
    },
    "de": {
        "eyebrow": "Fuer Solo-Creator gemacht &middot; Ohne Wasserzeichen &middot; Festpreis",
        "headline": "Stilvolle Untertitel in <em>Sekunden</em> &mdash; nie mit Wasserzeichen.",
        "lede": "Gemacht fuer TikTok-, Reels- und Shorts-Creator. Video hochladen, Sprache waehlen, sofort herunterladen.",
        "cta_scroll": "Kostenlos testen ↓",
        "free_note": "Kostenloser Plan: 3 Videos pro Monat, je bis zu 90 Sekunden &mdash; ohne Wasserzeichen. Bezahlplaene kommen bald.",
        "demo_label": "Beispiel fuer den Untertitel-Stil",
        "demo_caption": "So werden deine Untertitel aussehen.",
        "how_it_works_title": "So funktioniert's",
        "step1_title": "Video hochladen",
        "step1_desc": "Jede Videodatei, direkt vom Handy oder der Kamera.",
        "step2_title": "Sprache waehlen",
        "step2_desc": "Untertitel koennen in 14 Sprachen uebersetzt werden.",
        "step3_title": "Ohne Wasserzeichen herunterladen",
        "step3_desc": "Die meisten kurzen Clips sind in unter einer Minute fertig.",
        "faq_title": "Haeufig gestellte Fragen",
        "faq_q1": "Ist es wirklich kostenlos?",
        "faq_a1": "Ja. Der kostenlose Plan umfasst 3 Videos pro Monat, je bis zu 90 Sekunden, ganz ohne Wasserzeichen. Bezahlplaene fuer mehr Volumen kommen bald.",
        "faq_q2": "Welche Sprachen werden unterstuetzt?",
        "faq_a2": "Untertitel koennen in 14 Sprachen uebersetzt werden, und die Website selbst zeigt sich automatisch in deiner Sprache.",
        "faq_q3": "Hat mein Video ein Wasserzeichen?",
        "faq_a3": "Nie &mdash; weder im kostenlosen noch in einem zukuenftigen Bezahlplan.",
        "faq_q4": "Wie lange dauert es?",
        "faq_a4": "Die meisten kurzen Clips sind in unter einer Minute fertig.",
        "label_video": "Videodatei",
        "label_language": "Untertitelsprache",
        "label_email": "E-Mail-Adresse",
        "button_process": "Verarbeiten &rarr;",
        "badge_ready": "&#10003; Fertig",
        "result_headline": "Dein Video ist <em>fertig</em>.",
        "download": "Herunterladen &darr;",
        "back_link": "Weiteres Video verarbeiten &rarr;",
        "error_limit_title": "Du hast deine kostenlosen Videos fur diesen Monat aufgebraucht",
        "error_limit_body": "Der kostenlose Plan umfasst {limit} Videos pro Monat. Bezahlplane kommen bald.",
        "error_duration_title": "Video ist zu lang",
        "error_duration_body": "Der kostenlose Plan unterstuetzt Videos bis zu {max_min} Minuten. Versuch einen kuerzeren Clip.",
        "login_google": "Mit Google anmelden",
        "logout": "Abmelden",
        "login_prompt": "Melde dich mit Google an, um dein Video hochzuladen.",
        "pricing_title": "Preise",
        "pricing_pro_desc": "20 Videos pro Monat, je bis zu 5 Minuten — weiterhin ohne Wasserzeichen.",
        "pricing_soon": "Demnächst",
        "per_month": "/Monat",
        "processing_badge": "⏳ Wird verarbeitet",
        "processing_title": "Dein Video wird verarbeitet.",
        "processing_body": "Das kann bei längeren Clips einige Minuten dauern. Diese Seite aktualisiert sich automatisch, oder komm später wieder — wir schicken dir eine E-Mail, sobald es fertig ist.",
        "processing_error_title": "Etwas ist schiefgelaufen",
        "processing_error_body": "Wir konnten dein Video aufgrund eines unerwarteten Fehlers nicht verarbeiten. Bitte versuch es erneut oder melde dich, falls das weiterhin passiert.",
        "pricing_premium_desc": "10 Videos pro Monat, je bis zu 15 Minuten — weiterhin ohne Wasserzeichen.",
        "trust_note": "🔒 Verschlusselte Verbindung (HTTPS). Durch die Google-Anmeldung sehen oder speichern wir niemals ein Passwort. Videos werden nach der Verarbeitung automatisch von unseren Servern geloscht.",
        "cover_subs_label": "Video hat bereits eingebrannte Untertitel - abdecken",
        "cover_subs_hint": "Wir loeschen die alten Untertitel nicht - wir legen einen sauberen Balken darueber, bevor die neuen hinzugefuegt werden.",
        "cover_subs_before": "Wenn nicht ausgewaehlt",
        "cover_subs_after": "Wenn ausgewaehlt",
        "footer": "Subly wird von Nexi Digital entwickelt.",
    },
    "it": {
        "eyebrow": "Pensato per creator solo &middot; Senza filigrana &middot; Prezzo fisso",
        "headline": "Sottotitoli eleganti in <em>secondi</em> &mdash; mai con filigrana.",
        "lede": "Pensato per creator TikTok, Reels e Shorts. Carica il video, scegli una lingua, scarica subito.",
        "cta_scroll": "Provalo gratis ↓",
        "free_note": "Piano gratuito: 3 video al mese, fino a 90 secondi ciascuno &mdash; senza filigrana. Piani a pagamento in arrivo.",
        "demo_label": "Esempio di stile sottotitolo",
        "demo_caption": "Ecco come appariranno i tuoi sottotitoli.",
        "how_it_works_title": "Come funziona",
        "step1_title": "Carica il tuo video",
        "step1_desc": "Qualsiasi file video, direttamente da telefono o fotocamera.",
        "step2_title": "Scegli una lingua",
        "step2_desc": "I sottotitoli possono essere tradotti in 14 lingue.",
        "step3_title": "Scarica senza filigrana",
        "step3_desc": "La maggior parte dei clip brevi e pronta in meno di un minuto.",
        "faq_title": "Domande frequenti",
        "faq_q1": "E davvero gratis?",
        "faq_a1": "Si. Il piano gratuito include 3 video al mese, fino a 90 secondi ciascuno, senza alcuna filigrana. Piani a pagamento per piu volume in arrivo.",
        "faq_q2": "Quali lingue sono supportate?",
        "faq_a2": "I sottotitoli possono essere tradotti in 14 lingue, e il sito stesso si mostra automaticamente nella tua lingua.",
        "faq_q3": "Il mio video avra una filigrana?",
        "faq_a3": "Mai &mdash; ne sul piano gratuito, ne su un futuro piano a pagamento.",
        "faq_q4": "Quanto tempo ci vuole?",
        "faq_a4": "La maggior parte dei clip brevi e pronta in meno di un minuto.",
        "label_video": "File video",
        "label_language": "Lingua sottotitoli",
        "label_email": "Indirizzo email",
        "button_process": "Elabora &rarr;",
        "badge_ready": "&#10003; Pronto",
        "result_headline": "Il tuo video e <em>pronto</em>.",
        "download": "Scarica &darr;",
        "back_link": "Elabora un altro video &rarr;",
        "error_limit_title": "Hai usato i video gratuiti di questo mese",
        "error_limit_body": "Il piano gratuito include {limit} video al mese. I piani a pagamento arrivano presto.",
        "error_duration_title": "Il video e troppo lungo",
        "error_duration_body": "Il piano gratuito supporta video fino a {max_min} minuti. Prova una clip piu corta.",
        "login_google": "Accedi con Google",
        "logout": "Esci",
        "login_prompt": "Accedi con Google per caricare il tuo video.",
        "pricing_title": "Prezzi",
        "pricing_pro_desc": "20 video al mese, fino a 5 minuti ciascuno — sempre senza filigrana.",
        "pricing_soon": "Prossimamente",
        "per_month": "/mese",
        "processing_badge": "⏳ Elaborazione in corso",
        "processing_title": "Il tuo video è in elaborazione.",
        "processing_body": "Per i clip più lunghi può richiedere alcuni minuti. Questa pagina si aggiorna automaticamente, oppure torna più tardi — ti invieremo un'email quando sarà pronto.",
        "processing_error_title": "Qualcosa è andato storto",
        "processing_error_body": "Non siamo riusciti a elaborare il tuo video a causa di un errore imprevisto. Riprova, oppure contattaci se il problema persiste.",
        "pricing_premium_desc": "10 video al mese, fino a 15 minuti ciascuno — sempre senza filigrana.",
        "trust_note": "🔒 Connessione crittografata (HTTPS). Con l'accesso Google non vediamo ne conserviamo mai una password. I video vengono eliminati automaticamente dai nostri server dopo l'elaborazione.",
        "cover_subs_label": "Il video ha gia sottotitoli incorporati - coprili",
        "cover_subs_hint": "Non cancelliamo i vecchi sottotitoli - mettiamo una barra pulita sopra prima di aggiungere quelli nuovi.",
        "cover_subs_before": "Se non selezionato",
        "cover_subs_after": "Se selezionato",
        "footer": "Subly e sviluppato da Nexi Digital.",
    },
    "tr": {
        "eyebrow": "Solo icerik ureticileri icin &middot; Watermark'siz &middot; Sabit fiyat",
        "headline": "Videona <em>saniyeler icinde</em> stilli altyazi &mdash; asla watermark'li degil.",
        "lede": "TikTok, Reels ve Shorts icerik ureticileri icin. Videonu yukle, dilini sec, aninda indir.",
        "cta_scroll": "Ucretsiz dene ↓",
        "free_note": "Ucretsiz plan: ayda 3 video, video basina 90 saniyeye kadar &mdash; watermark'siz. Ucretli planlar yakinda.",
        "demo_label": "Ornek altyazi gorunumu",
        "demo_caption": "Altyazilarin boyle gorunecek.",
        "how_it_works_title": "Nasil calisir",
        "step1_title": "Videonu yukle",
        "step1_desc": "Telefonundan ya da kameradan herhangi bir video dosyasi.",
        "step2_title": "Dilini sec",
        "step2_desc": "Altyazilar 14 dile cevrilebilir.",
        "step3_title": "Watermark'siz indir",
        "step3_desc": "Kisa videolarin cogu bir dakikadan kisa surede hazir olur.",
        "faq_title": "Sik sorulan sorular",
        "faq_q1": "Gercekten ucretsiz mi?",
        "faq_a1": "Evet. Ucretsiz plan ayda 3 video, video basina 90 saniyeye kadar ve tamamen watermark'siz. Daha fazla hacim icin ucretli planlar yakinda geliyor.",
        "faq_q2": "Hangi diller destekleniyor?",
        "faq_a2": "Altyazilar 14 dile cevrilebilir, sitenin kendisi de otomatik olarak senin dilinde acilir.",
        "faq_q3": "Videomda watermark olacak mi?",
        "faq_a3": "Asla &mdash; ne ucretsiz planda, ne de ileride gelecek ucretli planlarda.",
        "faq_q4": "Ne kadar surer?",
        "faq_a4": "Kisa videolarin cogu bir dakikadan kisa surede hazir olur.",
        "label_video": "Video dosyasi",
        "label_language": "Altyazi dili",
        "label_email": "E-posta adresi",
        "button_process": "Isle &rarr;",
        "badge_ready": "&#10003; Hazir",
        "result_headline": "Video<em>n</em> hazir.",
        "download": "Indir &darr;",
        "back_link": "Baska video isle &rarr;",
        "error_limit_title": "Bu ayki ucretsiz video hakkini kullandin",
        "error_limit_body": "Ucretsiz plan ayda {limit} video icerir. Ucretli planlar yakinda geliyor!",
        "error_duration_title": "Video cok uzun",
        "error_duration_body": "Ucretsiz planda videolar en fazla {max_min} dakika olabilir. Daha kisa bir video dene.",
        "login_google": "Google ile giris yap",
        "logout": "Cikis yap",
        "login_prompt": "Videonu yuklemek icin Google ile giris yap.",
        "pricing_title": "Fiyatlandirma",
        "pricing_pro_desc": "Ayda 20 video, video basina 5 dakikaya kadar — yine watermark'siz.",
        "pricing_soon": "Yakinda",
        "per_month": "/ay",
        "processing_badge": "⏳ Isleniyor",
        "processing_title": "Video isleniyor.",
        "processing_body": "Uzun videolarda bu birkac dakika surebilir. Bu sayfa otomatik yenilenir, istersen daha sonra da donebilirsin — hazir oldugunda email atacagiz.",
        "processing_error_title": "Bir seyler ters gitti",
        "processing_error_body": "Videonu islerken beklenmedik bir hata olustu. Lutfen tekrar dene, sorun devam ederse bize ulas.",
        "pricing_premium_desc": "Ayda 10 video, video basina 15 dakikaya kadar — yine watermark'siz.",
        "trust_note": "🔒 Baglantin sifreli (HTTPS). Google ile giris yaptigin icin sifreni hicbir zaman gormuyor ya da saklamiyoruz. Videolar islem bitince sunucularimizdan otomatik olarak siliniyor.",
        "cover_subs_label": "Videoda zaten yakilmis (goruntuye islenmis) bir altyazi var, ustunu kapat",
        "cover_subs_hint": "Eski altyaziyi goruntuden silmiyoruz, yeni altyaziyi eklemeden once ustune temiz bir serit koyuyoruz.",
        "cover_subs_before": "Secilmezse",
        "cover_subs_after": "Secilirse",
        "footer": "Subly, Nexi Digital tarafindan gelistirilmistir.",
    },
    "ar": {
        "eyebrow": "مصمم لصناع المحتوى الفرديين &middot; بدون علامة مائية &middot; سعر ثابت",
        "headline": "ترجمات أنيقة لفيديوك في <em>ثوانٍ</em> &mdash; بدون علامة مائية أبدًا.",
        "lede": "مصمم لصناع محتوى TikTok وReels وShorts. ارفع الفيديو، اختر اللغة، وحمّله فورًا.",
        "cta_scroll": "جربه مجانًا ↓",
        "free_note": "الخطة المجانية: 3 فيديوهات شهريًا، حتى 90 ثانية لكل منها &mdash; بدون علامة مائية. الخطط المدفوعة قادمة قريبًا.",
        "demo_label": "مثال على شكل الترجمة",
        "demo_caption": "هكذا ستبدو ترجماتك.",
        "how_it_works_title": "كيف يعمل",
        "step1_title": "ارفع الفيديو",
        "step1_desc": "أي ملف فيديو، مباشرة من هاتفك أو كاميرتك.",
        "step2_title": "اختر اللغة",
        "step2_desc": "يمكن ترجمة الترجمات إلى 14 لغة.",
        "step3_title": "حمّله بدون علامة مائية",
        "step3_desc": "معظم المقاطع القصيرة تكون جاهزة في أقل من دقيقة.",
        "faq_title": "الأسئلة الشائعة",
        "faq_q1": "هل هو مجاني فعلاً؟",
        "faq_a1": "نعم. تشمل الخطة المجانية 3 فيديوهات شهريًا، حتى 90 ثانية لكل منها، بدون أي علامة مائية. الخطط المدفوعة لمزيد من الحجم قادمة قريبًا.",
        "faq_q2": "ما هي اللغات المدعومة؟",
        "faq_a2": "يمكن ترجمة الترجمات إلى 14 لغة، ويظهر الموقع نفسه تلقائيًا بلغتك.",
        "faq_q3": "هل سيكون هناك علامة مائية على فيديوي؟",
        "faq_a3": "أبدًا &mdash; لا في الخطة المجانية ولا في أي خطة مدفوعة مستقبلية.",
        "faq_q4": "كم من الوقت يستغرق؟",
        "faq_a4": "معظم المقاطع القصيرة تكون جاهزة في أقل من دقيقة.",
        "label_video": "ملف الفيديو",
        "label_language": "لغة الترجمة",
        "label_email": "البريد الإلكتروني",
        "button_process": "معالجة &larr;",
        "badge_ready": "&#10003; جاهز",
        "result_headline": "فيديوك <em>جاهز</em>.",
        "download": "تحميل &darr;",
        "back_link": "معالجة فيديو آخر &larr;",
        "error_limit_title": "لقد استخدمت فيديوهاتك المجانية لهذا الشهر",
        "error_limit_body": "تشمل الخطة المجانية {limit} فيديو شهريًا. الخطط المدفوعة قادمة قريبًا.",
        "error_duration_title": "الفيديو طويل جدًا",
        "error_duration_body": "تدعم الخطة المجانية فيديوهات حتى {max_min} دقيقة. جرب مقطعًا أقصر.",
        "login_google": "تسجيل الدخول بواسطة Google",
        "logout": "تسجيل الخروج",
        "login_prompt": "سجّل الدخول بواسطة Google لرفع الفيديو.",
        "pricing_title": "الأسعار",
        "pricing_pro_desc": "20 فيديو شهريًا، حتى 5 دقائق لكل منها — لا تزال بدون علامة مائية.",
        "pricing_soon": "قريبًا",
        "per_month": "/شهريًا",
        "processing_badge": "⏳ قيد المعالجة",
        "processing_title": "جارٍ معالجة فيديوك.",
        "processing_body": "قد يستغرق هذا بضع دقائق للمقاطع الأطول. تتحدث هذه الصفحة تلقائيًا، أو عد لاحقًا — سنرسل لك بريدًا إلكترونيًا عند الانتهاء.",
        "processing_error_title": "حدث خطأ ما",
        "processing_error_body": "لم نتمكن من معالجة فيديوك بسبب خطأ غير متوقع. يرجى المحاولة مرة أخرى، أو التواصل معنا إذا استمرت المشكلة.",
        "pricing_premium_desc": "10 فيديو شهريًا، حتى 15 دقيقة لكل منها — لا تزال بدون علامة مائية.",
        "trust_note": "🔒 اتصال مشفر (HTTPS). بفضل تسجيل الدخول عبر Google، لا نرى كلمة المرور الخاصة بك أبدًا ولا نخزنها. يتم حذف الفيديوهات تلقائيًا من خوادمنا بعد المعالجة.",
        "cover_subs_label": "الفيديو يحتوي بالفعل على ترجمة محفورة - قم بتغطيتها",
        "cover_subs_hint": "لن نمحو الترجمة القديمة، بل سنضع شريطًا نظيفًا فوقها قبل إضافة الترجمة الجديدة.",
        "cover_subs_before": "إذا لم يتم التحديد",
        "cover_subs_after": "إذا تم التحديد",
        "footer": "تم تطوير Subly بواسطة Nexi Digital.",
    },
    "hi": {
        "eyebrow": "सोलो क्रिएटर्स के लिए &middot; वॉटरमार्क-मुक्त &middot; निश्चित मूल्य",
        "headline": "आपके वीडियो के लिए <em>सेकंडों</em> में स्टाइलिश कैप्शन &mdash; कभी वॉटरमार्क नहीं।",
        "lede": "TikTok, Reels और Shorts क्रिएटर्स के लिए बनाया गया। वीडियो अपलोड करें, भाषा चुनें, तुरंत डाउनलोड करें।",
        "cta_scroll": "मुफ़्त में आज़माएं ↓",
        "free_note": "मुफ़्त योजना: महीने में 3 वीडियो, हर एक 90 सेकंड तक &mdash; वॉटरमार्क-मुक्त। सशुल्क योजनाएं जल्द आ रही हैं।",
        "demo_label": "कैप्शन स्टाइल का उदाहरण",
        "demo_caption": "आपके कैप्शन ऐसे दिखेंगे।",
        "how_it_works_title": "यह कैसे काम करता है",
        "step1_title": "अपना वीडियो अपलोड करें",
        "step1_desc": "आपके फ़ोन या कैमरे से कोई भी वीडियो फ़ाइल।",
        "step2_title": "एक भाषा चुनें",
        "step2_desc": "कैप्शन को 14 भाषाओं में अनुवादित किया जा सकता है।",
        "step3_title": "वॉटरमार्क-मुक्त डाउनलोड करें",
        "step3_desc": "अधिकतर छोटे क्लिप एक मिनट से कम समय में तैयार हो जाते हैं।",
        "faq_title": "अक्सर पूछे जाने वाले सवाल",
        "faq_q1": "क्या यह वाकई मुफ़्त है?",
        "faq_a1": "हां। मुफ़्त योजना में महीने में 3 वीडियो, हर एक 90 सेकंड तक, बिना किसी वॉटरमार्क के शामिल हैं। अधिक वॉल्यूम के लिए सशुल्क योजनाएं जल्द आ रही हैं।",
        "faq_q2": "कौन सी भाषाएं समर्थित हैं?",
        "faq_a2": "कैप्शन को 14 भाषाओं में अनुवादित किया जा सकता है, और साइट खुद अपने आप आपकी भाषा में दिखती है।",
        "faq_q3": "क्या मेरे वीडियो पर वॉटरमार्क होगा?",
        "faq_a3": "कभी नहीं &mdash; न मुफ़्त योजना में, न किसी भविष्य की सशुल्क योजना में।",
        "faq_q4": "इसमें कितना समय लगता है?",
        "faq_a4": "अधिकतर छोटे क्लिप एक मिनट से कम समय में तैयार हो जाते हैं।",
        "label_video": "वीडियो फ़ाइल",
        "label_language": "कैप्शन भाषा",
        "label_email": "ईमेल पता",
        "button_process": "प्रोसेस करें &rarr;",
        "badge_ready": "&#10003; तैयार",
        "result_headline": "आपका वीडियो <em>तैयार</em> है।",
        "download": "डाउनलोड करें &darr;",
        "back_link": "एक और वीडियो प्रोसेस करें &rarr;",
        "error_limit_title": "आपने इस महीने के मुफ़्त वीडियो इस्तेमाल कर लिए हैं",
        "error_limit_body": "मुफ़्त योजना में हर महीने {limit} वीडियो शामिल हैं। सशुल्क योजनाएं जल्द आ रही हैं।",
        "error_duration_title": "वीडियो बहुत लंबा है",
        "error_duration_body": "मुफ़्त योजना में {max_min} मिनट तक के वीडियो चलते हैं। एक छोटा क्लिप आज़माएं।",
        "login_google": "Google से साइन इन करें",
        "logout": "साइन आउट करें",
        "login_prompt": "अपना वीडियो अपलोड करने के लिए Google से साइन इन करें।",
        "pricing_title": "मूल्य निर्धारण",
        "pricing_pro_desc": "महीने में 20 वीडियो, हर एक 5 मिनट तक — फिर भी वॉटरमार्क-मुक्त।",
        "pricing_soon": "जल्द आ रहा है",
        "per_month": "/माह",
        "processing_badge": "⏳ प्रोसेस हो रहा है",
        "processing_title": "आपका वीडियो प्रोसेस हो रहा है।",
        "processing_body": "लंबे क्लिप के लिए इसमें कुछ मिनट लग सकते हैं। यह पेज अपने आप रिफ्रेश होता है, या बाद में वापस आएं — तैयार होने पर हम आपको ईमेल करेंगे।",
        "processing_error_title": "कुछ गलत हो गया",
        "processing_error_body": "अनपेक्षित त्रुटि के कारण हम आपका वीडियो प्रोसेस नहीं कर सके। कृपया दोबारा कोशिश करें, या यह जारी रहने पर हमसे संपर्क करें।",
        "pricing_premium_desc": "महीने में 10 वीडियो, हर एक 15 मिनट तक — फिर भी वॉटरमार्क-मुक्त।",
        "trust_note": "🔒 आपका कनेक्शन एन्क्रिप्टेड (HTTPS) है। Google साइन-इन के कारण हम कभी भी पासवर्ड नहीं देखते या सहेजते। प्रोसेसिंग के बाद वीडियो हमारे सर्वर से अपने आप हटा दिए जाते हैं।",
        "cover_subs_label": "वीडियो में पहले से ही जली हुई सबटाइटल है - उसे ढकें",
        "cover_subs_hint": "हम पुरानी सबटाइटल मिटाते नहीं, नई जोड़ने से पहले उसके ऊपर एक साफ पट्टी लगाते हैं।",
        "cover_subs_before": "अगर नहीं चुना गया",
        "cover_subs_after": "अगर चुना गया",
        "footer": "Subly, Nexi Digital द्वारा बनाया गया है।",
    },
    "zh": {
        "eyebrow": "为独立创作者打造 &middot; 无水印 &middot; 固定价格",
        "headline": "几<em>秒钟</em>内为你的视频添加精美字幕 &mdash; 永不添加水印。",
        "lede": "专为 TikTok、Reels 和 Shorts 创作者打造。上传视频，选择语言，立即下载。",
        "cta_scroll": "免费试用 ↓",
        "free_note": "免费计划：每月 3 个视频，每个最长 90 秒 &mdash; 无水印。付费计划即将推出。",
        "demo_label": "字幕样式示例",
        "demo_caption": "你的字幕将会是这样。",
        "how_it_works_title": "使用方法",
        "step1_title": "上传视频",
        "step1_desc": "任何视频文件，直接来自手机或相机。",
        "step2_title": "选择语言",
        "step2_desc": "字幕可翻译成 14 种语言。",
        "step3_title": "无水印下载",
        "step3_desc": "大多数短视频不到一分钟即可完成。",
        "faq_title": "常见问题",
        "faq_q1": "真的免费吗？",
        "faq_a1": "是的。免费计划每月包含 3 个视频，每个最长 90 秒，完全没有水印。更多用量的付费计划即将推出。",
        "faq_q2": "支持哪些语言？",
        "faq_a2": "字幕可翻译成 14 种语言，网站本身也会自动以你的语言显示。",
        "faq_q3": "我的视频会有水印吗？",
        "faq_a3": "绝不会 &mdash; 无论是免费计划还是未来的付费计划。",
        "faq_q4": "需要多长时间？",
        "faq_a4": "大多数短视频不到一分钟即可完成。",
        "label_video": "视频文件",
        "label_language": "字幕语言",
        "label_email": "电子邮箱",
        "button_process": "处理 &rarr;",
        "badge_ready": "&#10003; 已完成",
        "result_headline": "你的视频已<em>完成</em>。",
        "download": "下载 &darr;",
        "back_link": "处理另一个视频 &rarr;",
        "error_limit_title": "本月免费视频额度已用完",
        "error_limit_body": "免费计划每月包含 {limit} 个视频。付费计划即将推出。",
        "error_duration_title": "视频太长",
        "error_duration_body": "免费计划支持最长 {max_min} 分钟的视频。请尝试更短的片段。",
        "login_google": "使用 Google 登录",
        "logout": "退出登录",
        "login_prompt": "使用 Google 登录后即可上传视频。",
        "pricing_title": "价格",
        "pricing_pro_desc": "每月 20 个视频，每个最长 5 分钟 — 依然无水印。",
        "pricing_soon": "即将推出",
        "per_month": "/月",
        "processing_badge": "⏳ 处理中",
        "processing_title": "你的视频正在处理中。",
        "processing_body": "较长的片段可能需要几分钟。此页面会自动刷新，你也可以稍后再来查看——处理完成后我们会给你发邮件。",
        "processing_error_title": "出了点问题",
        "processing_error_body": "由于意外错误，我们无法处理你的视频。请重试，如果问题持续存在，请联系我们。",
        "pricing_premium_desc": "每月 10 个视频，每个最长 15 分钟 — 依然无水印。",
        "trust_note": "🔒 连接已加密 (HTTPS)。通过 Google 登录，我们从不查看或存储密码。视频在处理完成后会自动从我们的服务器上删除。",
        "cover_subs_label": "视频中已有烧录字幕 - 遮盖它",
        "cover_subs_hint": "我们不会擦除旧字幕，而是在添加新字幕之前在其上方放置一个干净的条块。",
        "cover_subs_before": "未选择时",
        "cover_subs_after": "选择后",
        "footer": "Subly 由 Nexi Digital 开发。",
    },
    "ja": {
        "eyebrow": "ソロクリエイターのために &middot; 透かしなし &middot; 定額料金",
        "headline": "<em>数秒</em>でスタイリッシュな字幕 &mdash; 透かしは一切なし。",
        "lede": "TikTok、Reels、Shorts クリエイターのために作られました。動画をアップロードし、言語を選んで、すぐにダウンロード。",
        "cta_scroll": "無料で試す ↓",
        "free_note": "無料プラン：月に3本、1本あたり最大90秒 &mdash; 透かしなし。有料プランは近日公開予定です。",
        "demo_label": "字幕スタイルの例",
        "demo_caption": "字幕はこのように表示されます。",
        "how_it_works_title": "使い方",
        "step1_title": "動画をアップロード",
        "step1_desc": "スマホやカメラからそのまま、どんな動画ファイルでもOK。",
        "step2_title": "言語を選ぶ",
        "step2_desc": "字幕は14言語に翻訳できます。",
        "step3_title": "透かしなしでダウンロード",
        "step3_desc": "ほとんどの短い動画は1分以内に完成します。",
        "faq_title": "よくある質問",
        "faq_q1": "本当に無料ですか？",
        "faq_a1": "はい。無料プランは月に3本、1本あたり最大90秒、透かしは一切ありません。より多く使いたい方向けの有料プランも近日公開予定です。",
        "faq_q2": "対応言語は？",
        "faq_a2": "字幕は14言語に翻訳でき、サイト自体も自動的にあなたの言語で表示されます。",
        "faq_q3": "動画に透かしは入りますか？",
        "faq_a3": "入りません &mdash; 無料プランでも、将来の有料プランでも。",
        "faq_q4": "どのくらい時間がかかりますか？",
        "faq_a4": "ほとんどの短い動画は1分以内に完成します。",
        "label_video": "動画ファイル",
        "label_language": "字幕の言語",
        "label_email": "メールアドレス",
        "button_process": "処理する &rarr;",
        "badge_ready": "&#10003; 完了",
        "result_headline": "動画の準備が<em>できました</em>。",
        "download": "ダウンロード &darr;",
        "back_link": "別の動画を処理する &rarr;",
        "error_limit_title": "今月の無料動画枠を使い切りました",
        "error_limit_body": "無料プランは月に{limit}本まで利用できます。有料プランは近日公開予定です。",
        "error_duration_title": "動画が長すぎます",
        "error_duration_body": "無料プランは最大{max_min}分の動画に対応しています。短い動画をお試しください。",
        "login_google": "Googleでログイン",
        "logout": "ログアウト",
        "login_prompt": "動画をアップロードするにはGoogleでログインしてください。",
        "pricing_title": "料金",
        "pricing_pro_desc": "月に20本、1本あたり最大5分 — 引き続き透かしなし。",
        "pricing_soon": "近日公開",
        "per_month": "/月",
        "processing_badge": "⏳ 処理中",
        "processing_title": "動画を処理しています。",
        "processing_body": "長い動画の場合、数分かかることがあります。このページは自動的に更新されます。後で戻ってきても構いません — 準備ができたらメールでお知らせします。",
        "processing_error_title": "問題が発生しました",
        "processing_error_body": "予期しないエラーにより動画を処理できませんでした。もう一度お試しいただくか、問題が続く場合はご連絡ください。",
        "pricing_premium_desc": "月に10本、1本あたり最大15分 — 引き続き透かしなし。",
        "trust_note": "🔒 接続は暗号化されています（HTTPS）。Googleログインを利用しているため、パスワードを見たり保存したりすることはありません。動画は処理後、サーバーから自動的に削除されます。",
        "cover_subs_label": "動画にすでに焼き込み字幕がある - それを隠す",
        "cover_subs_hint": "古い字幕は消しません。新しい字幕を追加する前に、その上にきれいなバーを配置します。",
        "cover_subs_before": "選択しない場合",
        "cover_subs_after": "選択した場合",
        "footer": "Subly は Nexi Digital が開発しています。",
    },
    "ko": {
        "eyebrow": "1인 크리에이터를 위한 &middot; 워터마크 없음 &middot; 고정 요금",
        "headline": "<em>몇 초 만에</em> 스타일리시한 자막 &mdash; 워터마크는 절대 없습니다.",
        "lede": "TikTok, Reels, Shorts 크리에이터를 위해 만들었습니다. 동영상을 업로드하고, 언어를 선택하고, 바로 다운로드하세요.",
        "cta_scroll": "무료로 사용해보기 ↓",
        "free_note": "무료 플랜: 월 3개 동영상, 각 최대 90초 &mdash; 워터마크 없음. 유료 플랜이 곧 출시됩니다.",
        "demo_label": "자막 스타일 예시",
        "demo_caption": "자막은 이렇게 보일 거예요.",
        "how_it_works_title": "이용 방법",
        "step1_title": "동영상 업로드",
        "step1_desc": "휴대폰이나 카메라에서 바로, 어떤 동영상 파일이든 가능합니다.",
        "step2_title": "언어 선택",
        "step2_desc": "자막은 14개 언어로 번역할 수 있습니다.",
        "step3_title": "워터마크 없이 다운로드",
        "step3_desc": "대부분의 짧은 클립은 1분 이내에 완성됩니다.",
        "faq_title": "자주 묻는 질문",
        "faq_q1": "정말 무료인가요?",
        "faq_a1": "네. 무료 플랜은 월 3개 동영상, 각 최대 90초까지 워터마크 없이 제공됩니다. 더 많은 용량을 위한 유료 플랜이 곧 출시됩니다.",
        "faq_q2": "어떤 언어를 지원하나요?",
        "faq_a2": "자막은 14개 언어로 번역할 수 있으며, 사이트 자체도 자동으로 사용자의 언어로 표시됩니다.",
        "faq_q3": "동영상에 워터마크가 생기나요?",
        "faq_a3": "절대 아닙니다 &mdash; 무료 플랜이든 향후 유료 플랜이든요.",
        "faq_q4": "얼마나 걸리나요?",
        "faq_a4": "대부분의 짧은 클립은 1분 이내에 완성됩니다.",
        "label_video": "동영상 파일",
        "label_language": "자막 언어",
        "label_email": "이메일 주소",
        "button_process": "처리하기 &rarr;",
        "badge_ready": "&#10003; 완료",
        "result_headline": "동영상이 <em>준비</em>되었습니다.",
        "download": "다운로드 &darr;",
        "back_link": "다른 동영상 처리하기 &rarr;",
        "error_limit_title": "이번 달 무료 동영상을 모두 사용했습니다",
        "error_limit_body": "무료 플랜은 월 {limit}개의 동영상을 제공합니다. 유료 플랜이 곧 출시됩니다.",
        "error_duration_title": "동영상이 너무 깁니다",
        "error_duration_body": "무료 플랜은 최대 {max_min}분 동영상을 지원합니다. 더 짧은 클립을 시도해 보세요.",
        "login_google": "Google로 로그인",
        "logout": "로그아웃",
        "login_prompt": "동영상을 업로드하려면 Google로 로그인하세요.",
        "pricing_title": "요금제",
        "pricing_pro_desc": "월 20개 동영상, 각 최대 5분 — 여전히 워터마크 없음.",
        "pricing_soon": "곧 출시",
        "per_month": "/월",
        "processing_badge": "⏳ 처리 중",
        "processing_title": "동영상을 처리하고 있습니다.",
        "processing_body": "긴 클립의 경우 몇 분 정도 걸릴 수 있습니다. 이 페이지는 자동으로 새로고침됩니다. 나중에 다시 확인하셔도 됩니다 — 준비되면 이메일로 알려드릴게요.",
        "processing_error_title": "문제가 발생했습니다",
        "processing_error_body": "예기치 않은 오류로 동영상을 처리하지 못했습니다. 다시 시도하시거나 문제가 계속되면 문의해 주세요.",
        "pricing_premium_desc": "월 10개 동영상, 각 최대 15분 — 여전히 워터마크 없음.",
        "trust_note": "🔒 연결은 암호화되어 있습니다 (HTTPS). Google 로그인을 사용하므로 비밀번호를 보거나 저장하지 않습니다. 동영상은 처리 후 서버에서 자동으로 삭제됩니다.",
        "cover_subs_label": "비디오에 이미 삽입된 자막이 있음 - 가리기",
        "cover_subs_hint": "기존 자막을 지우지는 않습니다. 새 자막을 추가하기 전에 그 위에 깔끔한 바를 놓습니다.",
        "cover_subs_before": "선택하지 않으면",
        "cover_subs_after": "선택하면",
        "footer": "Subly는 Nexi Digital이 개발했습니다.",
    },
    "ru": {
        "eyebrow": "Создано для соло-авторов &middot; Без водяного знака &middot; Фиксированная цена",
        "headline": "Стильные субтитры за <em>секунды</em> &mdash; без водяного знака, никогда.",
        "lede": "Создано для авторов TikTok, Reels и Shorts. Загрузите клип, выберите язык, скачайте сразу.",
        "cta_scroll": "Попробовать бесплатно ↓",
        "free_note": "Бесплатный план: 3 видео в месяц, до 90 секунд каждое &mdash; без водяного знака. Платные планы скоро появятся.",
        "demo_label": "Пример стиля субтитров",
        "demo_caption": "Вот как будут выглядеть ваши субтитры.",
        "how_it_works_title": "Как это работает",
        "step1_title": "Загрузите клип",
        "step1_desc": "Любой видеофайл, прямо с телефона или камеры.",
        "step2_title": "Выберите язык",
        "step2_desc": "Субтитры можно перевести на 14 языков.",
        "step3_title": "Скачайте без водяного знака",
        "step3_desc": "Большинство коротких клипов готовы менее чем за минуту.",
        "faq_title": "Часто задаваемые вопросы",
        "faq_q1": "Это правда бесплатно?",
        "faq_a1": "Да. Бесплатный план включает 3 видео в месяц, до 90 секунд каждое, без единого водяного знака. Платные планы для большего объёма скоро появятся.",
        "faq_q2": "Какие языки поддерживаются?",
        "faq_a2": "Субтитры можно перевести на 14 языков, а сам сайт автоматически отображается на вашем языке.",
        "faq_q3": "Будет ли водяной знак на моём видео?",
        "faq_a3": "Никогда &mdash; ни в бесплатном плане, ни в будущих платных планах.",
        "faq_q4": "Сколько это занимает времени?",
        "faq_a4": "Большинство коротких клипов готовы менее чем за минуту.",
        "label_video": "Видеофайл",
        "label_language": "Язык субтитров",
        "label_email": "Электронная почта",
        "button_process": "Обработать &rarr;",
        "badge_ready": "&#10003; Готово",
        "result_headline": "Ваше видео <em>готово</em>.",
        "download": "Скачать &darr;",
        "back_link": "Обработать другое видео &rarr;",
        "error_limit_title": "Вы использовали бесплатные видео за этот месяц",
        "error_limit_body": "Бесплатный план включает {limit} видео в месяц. Платные планы скоро появятся.",
        "error_duration_title": "Видео слишком длинное",
        "error_duration_body": "Бесплатный план поддерживает видео до {max_min} минут. Попробуйте более короткий ролик.",
        "login_google": "Войти через Google",
        "logout": "Выйти",
        "login_prompt": "Войдите через Google, чтобы загрузить видео.",
        "pricing_title": "Тарифы",
        "pricing_pro_desc": "20 видео в месяц, до 5 минут каждое — по-прежнему без водяного знака.",
        "pricing_soon": "Скоро",
        "per_month": "/мес",
        "processing_badge": "⏳ Обработка",
        "processing_title": "Ваше видео обрабатывается.",
        "processing_body": "Для более длинных роликов это может занять несколько минут. Страница обновляется автоматически, можно вернуться позже — мы пришлём письмо, когда всё будет готово.",
        "processing_error_title": "Что-то пошло не так",
        "processing_error_body": "Не удалось обработать ваше видео из-за непредвиденной ошибки. Попробуйте ещё раз или свяжитесь с нами, если проблема повторится.",
        "pricing_premium_desc": "10 видео в месяц, до 15 минут каждое — по-прежнему без водяного знака.",
        "trust_note": "🔒 Соединение зашифровано (HTTPS). Благодаря входу через Google мы никогда не видим и не храним пароль. Видео автоматически удаляются с наших серверов после обработки.",
        "cover_subs_label": "В видео уже есть вшитые субтитры - скрыть их",
        "cover_subs_hint": "Мы не стираем старые субтитры, а размещаем поверх них чистую полосу перед добавлением новых.",
        "cover_subs_before": "Если не выбрано",
        "cover_subs_after": "Если выбрано",
        "footer": "Subly разработан Nexi Digital.",
    },
    "id": {
        "eyebrow": "Dibuat untuk kreator solo &middot; Tanpa watermark &middot; Harga tetap",
        "headline": "Teks bergaya untuk videomu dalam <em>hitungan detik</em> &mdash; tanpa watermark, selamanya.",
        "lede": "Dibuat untuk kreator TikTok, Reels, dan Shorts. Unggah klipmu, pilih bahasa, unduh seketika.",
        "cta_scroll": "Coba gratis ↓",
        "free_note": "Paket gratis: 3 video per bulan, masing-masing hingga 90 detik &mdash; tanpa watermark. Paket berbayar segera hadir.",
        "demo_label": "Contoh gaya teks",
        "demo_caption": "Begini tampilan teksmu nanti.",
        "how_it_works_title": "Cara kerjanya",
        "step1_title": "Unggah klipmu",
        "step1_desc": "File video apa pun, langsung dari ponsel atau kamera.",
        "step2_title": "Pilih bahasa",
        "step2_desc": "Teks dapat diterjemahkan ke dalam 14 bahasa.",
        "step3_title": "Unduh tanpa watermark",
        "step3_desc": "Sebagian besar klip pendek siap dalam waktu kurang dari satu menit.",
        "faq_title": "Pertanyaan yang sering diajukan",
        "faq_q1": "Apakah benar-benar gratis?",
        "faq_a1": "Ya. Paket gratis mencakup 3 video per bulan, masing-masing hingga 90 detik, tanpa watermark sama sekali. Paket berbayar untuk volume lebih besar segera hadir.",
        "faq_q2": "Bahasa apa saja yang didukung?",
        "faq_a2": "Teks dapat diterjemahkan ke dalam 14 bahasa, dan situs itu sendiri otomatis tampil dalam bahasamu.",
        "faq_q3": "Apakah videoku akan ada watermark?",
        "faq_a3": "Tidak pernah &mdash; baik di paket gratis maupun paket berbayar di masa depan.",
        "faq_q4": "Berapa lama prosesnya?",
        "faq_a4": "Sebagian besar klip pendek siap dalam waktu kurang dari satu menit.",
        "label_video": "File video",
        "label_language": "Bahasa teks",
        "label_email": "Alamat email",
        "button_process": "Proses &rarr;",
        "badge_ready": "&#10003; Siap",
        "result_headline": "Videomu sudah <em>siap</em>.",
        "download": "Unduh &darr;",
        "back_link": "Proses video lain &rarr;",
        "error_limit_title": "Kamu sudah memakai jatah video gratis bulan ini",
        "error_limit_body": "Paket gratis mencakup {limit} video per bulan. Paket berbayar segera hadir.",
        "error_duration_title": "Video terlalu panjang",
        "error_duration_body": "Paket gratis mendukung video hingga {max_min} menit. Coba klip yang lebih pendek.",
        "login_google": "Masuk dengan Google",
        "logout": "Keluar",
        "login_prompt": "Masuk dengan Google untuk mengunggah videomu.",
        "pricing_title": "Harga",
        "pricing_pro_desc": "20 video per bulan, masing-masing hingga 5 menit — tetap tanpa watermark.",
        "pricing_soon": "Segera hadir",
        "per_month": "/bulan",
        "processing_badge": "⏳ Sedang diproses",
        "processing_title": "Videomu sedang diproses.",
        "processing_body": "Ini bisa memakan waktu beberapa menit untuk klip yang lebih panjang. Halaman ini akan refresh otomatis, atau kembali lagi nanti — kami akan mengirim email saat sudah siap.",
        "processing_error_title": "Ada yang tidak beres",
        "processing_error_body": "Kami tidak bisa memproses videomu karena kesalahan tak terduga. Coba lagi, atau hubungi kami jika masalah ini berlanjut.",
        "pricing_premium_desc": "10 video per bulan, masing-masing hingga 15 menit — tetap tanpa watermark.",
        "trust_note": "🔒 Koneksi terenkripsi (HTTPS). Dengan login Google, kami tidak pernah melihat atau menyimpan kata sandi. Video dihapus secara otomatis dari server kami setelah diproses.",
        "cover_subs_label": "Video sudah punya subtitle yang tertanam - tutupi",
        "cover_subs_hint": "Kami tidak menghapus subtitle lama, kami menempatkan bilah bersih di atasnya sebelum menambahkan yang baru.",
        "cover_subs_before": "Jika tidak dipilih",
        "cover_subs_after": "Jika dipilih",
        "footer": "Subly dikembangkan oleh Nexi Digital.",
    },
}


def get_ui_language(accept_languages, ip: str = "") -> str:
    country_lang = get_country_lang(ip)
    if country_lang:
        return country_lang
    match = accept_languages.best_match(SUPPORTED_UI_LANGS)
    return match or "en"


def get_ui_strings(lang: str) -> dict:
    return UI_STRINGS.get(lang, UI_STRINGS["en"])
