"""
Site arayuzunun (buton, baslik, etiket metinleri) cok dilli metinleri.
Altyazi diliyle (translate.py) karistirilmasin - bu, sitenin kendi dilidir,
ziyaretcinin taraycisi hangi dildeyse ona gore otomatik secilir.
"""

SUPPORTED_UI_LANGS = ["en", "es", "pt", "fr", "de", "it", "tr", "ar", "hi", "zh", "ja", "ko", "ru", "id"]
RTL_LANGS = {"ar"}

UI_STRINGS = {
    "en": {
        "eyebrow": "Watermark-Free &middot; Flat Price &middot; Multilingual",
        "headline": "Stylish captions for your video in <em>seconds</em>.",
        "lede": "Upload your video, pick a language, download watermark-free.",
        "label_video": "Video file",
        "label_language": "Caption language",
        "button_process": "Process &rarr;",
        "badge_ready": "&#10003; Ready",
        "result_headline": "Your video is <em>ready</em>.",
        "download": "Download &darr;",
        "back_link": "Process another video &rarr;",
        "footer": "Subly is built by Nexi Digital.",
    },
    "es": {
        "eyebrow": "Sin Marca de Agua &middot; Precio Fijo &middot; Multiidioma",
        "headline": "Subtitulos con estilo en <em>segundos</em>.",
        "lede": "Sube tu video, elige un idioma, descarga sin marca de agua.",
        "label_video": "Archivo de video",
        "label_language": "Idioma de subtitulos",
        "button_process": "Procesar &rarr;",
        "badge_ready": "&#10003; Listo",
        "result_headline": "Tu video esta <em>listo</em>.",
        "download": "Descargar &darr;",
        "back_link": "Procesar otro video &rarr;",
        "footer": "Subly esta construido por Nexi Digital.",
    },
    "pt": {
        "eyebrow": "Sem Marca d'Agua &middot; Preco Fixo &middot; Multilingue",
        "headline": "Legendas estilosas em <em>segundos</em>.",
        "lede": "Envie seu video, escolha um idioma, baixe sem marca d'agua.",
        "label_video": "Arquivo de video",
        "label_language": "Idioma da legenda",
        "button_process": "Processar &rarr;",
        "badge_ready": "&#10003; Pronto",
        "result_headline": "Seu video esta <em>pronto</em>.",
        "download": "Baixar &darr;",
        "back_link": "Processar outro video &rarr;",
        "footer": "Subly e desenvolvido pela Nexi Digital.",
    },
    "fr": {
        "eyebrow": "Sans Filigrane &middot; Prix Fixe &middot; Multilingue",
        "headline": "Des sous-titres stylises en <em>secondes</em>.",
        "lede": "Importez votre video, choisissez une langue, telechargez sans filigrane.",
        "label_video": "Fichier video",
        "label_language": "Langue des sous-titres",
        "button_process": "Traiter &rarr;",
        "badge_ready": "&#10003; Pret",
        "result_headline": "Votre video est <em>prete</em>.",
        "download": "Telecharger &darr;",
        "back_link": "Traiter une autre video &rarr;",
        "footer": "Subly est developpe par Nexi Digital.",
    },
    "de": {
        "eyebrow": "Ohne Wasserzeichen &middot; Festpreis &middot; Mehrsprachig",
        "headline": "Stilvolle Untertitel in <em>Sekunden</em>.",
        "lede": "Video hochladen, Sprache waehlen, ohne Wasserzeichen herunterladen.",
        "label_video": "Videodatei",
        "label_language": "Untertitelsprache",
        "button_process": "Verarbeiten &rarr;",
        "badge_ready": "&#10003; Fertig",
        "result_headline": "Dein Video ist <em>fertig</em>.",
        "download": "Herunterladen &darr;",
        "back_link": "Weiteres Video verarbeiten &rarr;",
        "footer": "Subly wird von Nexi Digital entwickelt.",
    },
    "it": {
        "eyebrow": "Senza Filigrana &middot; Prezzo Fisso &middot; Multilingua",
        "headline": "Sottotitoli eleganti in <em>secondi</em>.",
        "lede": "Carica il video, scegli una lingua, scarica senza filigrana.",
        "label_video": "File video",
        "label_language": "Lingua sottotitoli",
        "button_process": "Elabora &rarr;",
        "badge_ready": "&#10003; Pronto",
        "result_headline": "Il tuo video e <em>pronto</em>.",
        "download": "Scarica &darr;",
        "back_link": "Elabora un altro video &rarr;",
        "footer": "Subly e sviluppato da Nexi Digital.",
    },
    "tr": {
        "eyebrow": "Watermark'siz &middot; Sabit Fiyat &middot; Cok Dilli",
        "headline": "Videona <em>saniyeler icinde</em> stilli altyazi.",
        "lede": "Videonu yukle, dilini sec, watermark'siz olarak indir.",
        "label_video": "Video dosyasi",
        "label_language": "Altyazi dili",
        "button_process": "Isle &rarr;",
        "badge_ready": "&#10003; Hazir",
        "result_headline": "Video<em>n</em> hazir.",
        "download": "Indir &darr;",
        "back_link": "Baska video isle &rarr;",
        "footer": "Subly, Nexi Digital tarafindan gelistirilmistir.",
    },
    "ar": {
        "eyebrow": "بدون علامة مائية &middot; سعر ثابت &middot; متعدد اللغات",
        "headline": "ترجمات أنيقة لفيديوك في <em>ثوانٍ</em>.",
        "lede": "ارفع الفيديو، اختر اللغة، وحمّله بدون علامة مائية.",
        "label_video": "ملف الفيديو",
        "label_language": "لغة الترجمة",
        "button_process": "معالجة &larr;",
        "badge_ready": "&#10003; جاهز",
        "result_headline": "فيديوك <em>جاهز</em>.",
        "download": "تحميل &darr;",
        "back_link": "معالجة فيديو آخر &larr;",
        "footer": "تم تطوير Subly بواسطة Nexi Digital.",
    },
    "hi": {
        "eyebrow": "वॉटरमार्क-मुक्त &middot; निश्चित मूल्य &middot; बहुभाषी",
        "headline": "आपके वीडियो के लिए <em>सेकंडों</em> में स्टाइलिश कैप्शन।",
        "lede": "वीडियो अपलोड करें, भाषा चुनें, वॉटरमार्क-मुक्त डाउनलोड करें।",
        "label_video": "वीडियो फ़ाइल",
        "label_language": "कैप्शन भाषा",
        "button_process": "प्रोसेस करें &rarr;",
        "badge_ready": "&#10003; तैयार",
        "result_headline": "आपका वीडियो <em>तैयार</em> है।",
        "download": "डाउनलोड करें &darr;",
        "back_link": "एक और वीडियो प्रोसेस करें &rarr;",
        "footer": "Subly, Nexi Digital द्वारा बनाया गया है।",
    },
    "zh": {
        "eyebrow": "无水印 &middot; 固定价格 &middot; 多语言",
        "headline": "几<em>秒钟</em>内为你的视频添加精美字幕。",
        "lede": "上传视频，选择语言，无水印下载。",
        "label_video": "视频文件",
        "label_language": "字幕语言",
        "button_process": "处理 &rarr;",
        "badge_ready": "&#10003; 已完成",
        "result_headline": "你的视频已<em>完成</em>。",
        "download": "下载 &darr;",
        "back_link": "处理另一个视频 &rarr;",
        "footer": "Subly 由 Nexi Digital 开发。",
    },
    "ja": {
        "eyebrow": "透かしなし &middot; 定額料金 &middot; 多言語対応",
        "headline": "<em>数秒</em>でスタイリッシュな字幕。",
        "lede": "動画をアップロードし、言語を選んで、透かしなしでダウンロード。",
        "label_video": "動画ファイル",
        "label_language": "字幕の言語",
        "button_process": "処理する &rarr;",
        "badge_ready": "&#10003; 完了",
        "result_headline": "動画の準備が<em>できました</em>。",
        "download": "ダウンロード &darr;",
        "back_link": "別の動画を処理する &rarr;",
        "footer": "Subly は Nexi Digital が開発しています。",
    },
    "ko": {
        "eyebrow": "워터마크 없음 &middot; 고정 요금 &middot; 다국어 지원",
        "headline": "<em>몇 초 만에</em> 스타일리시한 자막.",
        "lede": "동영상을 업로드하고, 언어를 선택하고, 워터마크 없이 다운로드하세요.",
        "label_video": "동영상 파일",
        "label_language": "자막 언어",
        "button_process": "처리하기 &rarr;",
        "badge_ready": "&#10003; 완료",
        "result_headline": "동영상이 <em>준비</em>되었습니다.",
        "download": "다운로드 &darr;",
        "back_link": "다른 동영상 처리하기 &rarr;",
        "footer": "Subly는 Nexi Digital이 개발했습니다.",
    },
    "ru": {
        "eyebrow": "Без Водяного Знака &middot; Фиксированная Цена &middot; Многоязычный",
        "headline": "Стильные субтитры за <em>секунды</em>.",
        "lede": "Загрузите видео, выберите язык, скачайте без водяного знака.",
        "label_video": "Видеофайл",
        "label_language": "Язык субтитров",
        "button_process": "Обработать &rarr;",
        "badge_ready": "&#10003; Готово",
        "result_headline": "Ваше видео <em>готово</em>.",
        "download": "Скачать &darr;",
        "back_link": "Обработать другое видео &rarr;",
        "footer": "Subly разработан Nexi Digital.",
    },
    "id": {
        "eyebrow": "Tanpa Watermark &middot; Harga Tetap &middot; Multibahasa",
        "headline": "Teks bergaya untuk videomu dalam <em>hitungan detik</em>.",
        "lede": "Unggah videomu, pilih bahasa, unduh tanpa watermark.",
        "label_video": "File video",
        "label_language": "Bahasa teks",
        "button_process": "Proses &rarr;",
        "badge_ready": "&#10003; Siap",
        "result_headline": "Videomu sudah <em>siap</em>.",
        "download": "Unduh &darr;",
        "back_link": "Proses video lain &rarr;",
        "footer": "Subly dikembangkan oleh Nexi Digital.",
    },
}


def get_ui_language(accept_languages) -> str:
    match = accept_languages.best_match(SUPPORTED_UI_LANGS)
    return match or "en"


def get_ui_strings(lang: str) -> dict:
    return UI_STRINGS.get(lang, UI_STRINGS["en"])
